# Generated by Django 5.2.13 on 2026-04-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_location_friendrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='accounts_fr_sender__ee9283_idx',
            old_name='accounts_fr_sender_0cf811_idx',
        ),
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='accounts_fr_receive_625767_idx',
            old_name='accounts_fr_receive_4e5bbc_idx',
        ),
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='accounts_fr_status_53cc37_idx',
            old_name='accounts_fr_status_7d874b_idx',
        ),
    ]
