# Generated by Django 5.2.13 on 2026-04-16 22:36

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_privacy_controls"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.MessengerUserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="authactiontoken",
            new_name="accounts_au_user_id_0d60c4_idx",
            old_name="accounts_au_user_id_2ceb3f_idx",
        ),
        migrations.RenameIndex(
            model_name="authactiontoken",
            new_name="accounts_au_purpose_722ea7_idx",
            old_name="accounts_au_purpose_166f6f_idx",
        ),
        migrations.RenameIndex(
            model_name="socialaccount",
            new_name="accounts_so_user_id_0a462a_idx",
            old_name="accounts_so_user_id_a75664_idx",
        ),
        migrations.RenameIndex(
            model_name="socialaccount",
            new_name="accounts_so_provide_b76d35_idx",
            old_name="accounts_so_provider_9ee6ef_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="accounts_us_user_id_9fbea3_idx",
            old_name="accounts_us_user_id_3b8cca_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="accounts_us_user_id_9e8770_idx",
            old_name="accounts_us_user_id_7ed1f2_idx",
        ),
    ]
