from django.urls import path

from apps.support.api.views import (
    SupportAgentAvailabilityView,
    SupportAgentDetailView,
    SupportAgentInvitationAcceptView,
    SupportAgentInvitationDetailView,
    SupportAgentInvitationListCreateView,
    SupportAgentInvitationPreviewView,
    SupportAgentInvitationResendView,
    SupportBootstrapView,
    SupportConversationClaimView,
    SupportConversationDetailView,
    SupportConversationListView,
    SupportConversationMessagesView,
    SupportConversationReadView,
    SupportConversationUploadView,
    SupportAttachmentAccessView,
    SupportAttachmentPreviewView,
    SupportAttachmentThumbnailView,
    SupportUnreadSummaryView,
    SupportWebsiteDetailView,
    SupportWebsiteListCreateView,
    SupportWebsiteSiteKeyRegenerateView,
    SupportWebsiteWidgetSettingsView,
    SupportWebsiteWidgetConfigurationView,
    SupportWidgetConfigView,
    SupportWidgetSessionCreateView,
    SupportWidgetSessionDetailView,
    SupportWidgetSessionRefreshView,
    SupportWidgetConversationMessagesView,
    SupportWidgetConversationReadView,
    SupportWidgetConversationUploadView,
    SupportWidgetAttachmentAccessView,
    SupportWidgetAttachmentPreviewView,
    SupportWidgetAttachmentThumbnailView,
    SupportTagListCreateView,
    SupportTagDetailView,
    SupportCannedReplyListCreateView,
    SupportCannedReplyDetailView,
    SupportSavedInboxViewListCreateView,
    SupportSavedInboxViewDetailView,
    SupportConversationInternalNotesView,
    SupportConversationTagsView,
    SupportConversationActivityView,
    SupportServiceSettingsView,
    SupportServiceAlertListView,
    SupportServiceAlertReadView,
    SupportServiceAlertReadAllView,
    SupportFeedbackSettingsView,
    SupportAnalyticsOverviewView,
    SupportConversationCSATView,
    SupportWidgetConversationCSATView,
    SupportKnowledgeSettingsView,
    SupportKnowledgeCategoryListCreateView,
    SupportKnowledgeCategoryDetailView,
    SupportKnowledgeArticleListCreateView,
    SupportKnowledgeArticleDetailView,
    SupportWidgetKnowledgeListView,
    SupportWidgetKnowledgeArticleView,
    SupportWidgetKnowledgeFeedbackView,
    SupportPrivacySettingsView,
    SupportWebhookEndpointListCreateView,
    SupportWebhookEndpointDetailView,
    SupportWebhookEndpointSecretRotateView,
    SupportWebhookEndpointTestView,
    SupportWebhookDeliveryListView,
    SupportDataExportListCreateView,
    SupportDataExportDownloadView,
    SupportVisitorDeletionRequestListView,
    SupportVisitorDeletionRequestCreateView,
    SupportWidgetVisitorDeletionRequestView,
    SupportCallSettingsView,
    SupportActiveCallView,
    SupportConversationCallStartView,
    SupportCallDetailView,
    SupportCallEndView,
    SupportCallSignalView,
    SupportCallMediaStateView,
    SupportCallTurnCredentialsView,
    SupportWidgetActiveCallView,
    SupportWidgetCallDetailView,
    SupportWidgetCallAcceptView,
    SupportWidgetCallDeclineView,
    SupportWidgetCallEndView,
    SupportWidgetCallSignalView,
    SupportWidgetCallMediaStateView,
    SupportWidgetCallTurnCredentialsView,
)

urlpatterns = [
    path("call-settings/", SupportCallSettingsView.as_view(), name="support-call-settings"),
    path("calls/active/", SupportActiveCallView.as_view(), name="support-call-active"),
    path("calls/turn-credentials/", SupportCallTurnCredentialsView.as_view(), name="support-call-turn-credentials"),
    path("conversations/<uuid:conversation_id>/calls/", SupportConversationCallStartView.as_view(), name="support-call-start"),
    path("calls/<uuid:call_id>/", SupportCallDetailView.as_view(), name="support-call-detail"),
    path("calls/<uuid:call_id>/end/", SupportCallEndView.as_view(), name="support-call-end"),
    path("calls/<uuid:call_id>/signals/", SupportCallSignalView.as_view(), name="support-call-signals"),
    path("calls/<uuid:call_id>/media-state/", SupportCallMediaStateView.as_view(), name="support-call-media-state"),
    path("privacy/settings/", SupportPrivacySettingsView.as_view(), name="support-privacy-settings"),
    path("privacy/deletion-requests/", SupportVisitorDeletionRequestListView.as_view(), name="support-visitor-deletion-list"),
    path("privacy/visitors/<uuid:visitor_id>/delete/", SupportVisitorDeletionRequestCreateView.as_view(), name="support-visitor-deletion-create"),
    path("webhooks/", SupportWebhookEndpointListCreateView.as_view(), name="support-webhook-list-create"),
    path("webhooks/deliveries/", SupportWebhookDeliveryListView.as_view(), name="support-webhook-delivery-list"),
    path("webhooks/<uuid:endpoint_id>/", SupportWebhookEndpointDetailView.as_view(), name="support-webhook-detail"),
    path("webhooks/<uuid:endpoint_id>/rotate-secret/", SupportWebhookEndpointSecretRotateView.as_view(), name="support-webhook-secret-rotate"),
    path("webhooks/<uuid:endpoint_id>/test/", SupportWebhookEndpointTestView.as_view(), name="support-webhook-test"),
    path("exports/", SupportDataExportListCreateView.as_view(), name="support-export-list-create"),
    path("exports/<uuid:export_id>/download/", SupportDataExportDownloadView.as_view(), name="support-export-download"),
    path("knowledge/settings/", SupportKnowledgeSettingsView.as_view(), name="support-knowledge-settings"),
    path("knowledge/categories/", SupportKnowledgeCategoryListCreateView.as_view(), name="support-knowledge-category-list-create"),
    path("knowledge/categories/<uuid:category_id>/", SupportKnowledgeCategoryDetailView.as_view(), name="support-knowledge-category-detail"),
    path("knowledge/articles/", SupportKnowledgeArticleListCreateView.as_view(), name="support-knowledge-article-list-create"),
    path("knowledge/articles/<uuid:article_id>/", SupportKnowledgeArticleDetailView.as_view(), name="support-knowledge-article-detail"),
    path("feedback-settings/", SupportFeedbackSettingsView.as_view(), name="support-feedback-settings"),
    path("analytics/overview/", SupportAnalyticsOverviewView.as_view(), name="support-analytics-overview"),
    path("service-settings/", SupportServiceSettingsView.as_view(), name="support-service-settings"),
    path("service-alerts/", SupportServiceAlertListView.as_view(), name="support-service-alert-list"),
    path("service-alerts/read-all/", SupportServiceAlertReadAllView.as_view(), name="support-service-alert-read-all"),
    path("service-alerts/<uuid:alert_id>/read/", SupportServiceAlertReadView.as_view(), name="support-service-alert-read"),
    path("tags/", SupportTagListCreateView.as_view(), name="support-tag-list-create"),
    path("tags/<uuid:tag_id>/", SupportTagDetailView.as_view(), name="support-tag-detail"),
    path("canned-replies/", SupportCannedReplyListCreateView.as_view(), name="support-canned-reply-list-create"),
    path("canned-replies/<uuid:reply_id>/", SupportCannedReplyDetailView.as_view(), name="support-canned-reply-detail"),
    path("saved-views/", SupportSavedInboxViewListCreateView.as_view(), name="support-saved-view-list-create"),
    path("saved-views/<uuid:view_id>/", SupportSavedInboxViewDetailView.as_view(), name="support-saved-view-detail"),
    path("bootstrap/", SupportBootstrapView.as_view(), name="support-bootstrap"),
    path("conversations/", SupportConversationListView.as_view(), name="support-conversation-list"),
    path("unread-summary/", SupportUnreadSummaryView.as_view(), name="support-unread-summary"),
    path("conversations/<uuid:conversation_id>/", SupportConversationDetailView.as_view(), name="support-conversation-detail"),
    path("conversations/<uuid:conversation_id>/notes/", SupportConversationInternalNotesView.as_view(), name="support-conversation-notes"),
    path("conversations/<uuid:conversation_id>/tags/", SupportConversationTagsView.as_view(), name="support-conversation-tags"),
    path("conversations/<uuid:conversation_id>/activity/", SupportConversationActivityView.as_view(), name="support-conversation-activity"),
    path("conversations/<uuid:conversation_id>/csat/", SupportConversationCSATView.as_view(), name="support-conversation-csat"),
    path("conversations/<uuid:conversation_id>/messages/", SupportConversationMessagesView.as_view(), name="support-conversation-messages"),
    path("conversations/<uuid:conversation_id>/uploads/", SupportConversationUploadView.as_view(), name="support-conversation-upload"),
    path("conversations/<uuid:conversation_id>/read/", SupportConversationReadView.as_view(), name="support-conversation-read"),
    path("conversations/<uuid:conversation_id>/claim/", SupportConversationClaimView.as_view(), name="support-conversation-claim"),
    path("attachments/<uuid:attachment_id>/download/", SupportAttachmentAccessView.as_view(), name="support-attachment-download"),
    path("attachments/<uuid:attachment_id>/preview/", SupportAttachmentPreviewView.as_view(), name="support-attachment-preview"),
    path("attachments/<uuid:attachment_id>/thumbnail/", SupportAttachmentThumbnailView.as_view(), name="support-attachment-thumbnail"),
    path("websites/", SupportWebsiteListCreateView.as_view(), name="support-website-list-create"),
    path("websites/<uuid:website_id>/", SupportWebsiteDetailView.as_view(), name="support-website-detail"),
    path("websites/<uuid:website_id>/widget/", SupportWebsiteWidgetSettingsView.as_view(), name="support-website-widget-settings"),
    path("websites/<uuid:website_id>/widget-configuration/", SupportWebsiteWidgetConfigurationView.as_view(), name="support-website-widget-configuration"),
    path("websites/<uuid:website_id>/site-key/regenerate/", SupportWebsiteSiteKeyRegenerateView.as_view(), name="support-website-site-key-regenerate"),
    path("agents/invitations/", SupportAgentInvitationListCreateView.as_view(), name="support-agent-invitation-list-create"),
    path("agents/invitations/<uuid:invitation_id>/", SupportAgentInvitationDetailView.as_view(), name="support-agent-invitation-detail"),
    path("agents/invitations/<uuid:invitation_id>/resend/", SupportAgentInvitationResendView.as_view(), name="support-agent-invitation-resend"),
    path("agents/<uuid:agent_id>/", SupportAgentDetailView.as_view(), name="support-agent-detail"),
    path("agents/me/availability/", SupportAgentAvailabilityView.as_view(), name="support-agent-availability"),
    path("invitations/preview/", SupportAgentInvitationPreviewView.as_view(), name="support-agent-invitation-preview"),
    path("invitations/accept/", SupportAgentInvitationAcceptView.as_view(), name="support-agent-invitation-accept"),
    path("widget/<uuid:site_key>/config/", SupportWidgetConfigView.as_view(), name="support-widget-config"),
    path("widget/<uuid:site_key>/knowledge/", SupportWidgetKnowledgeListView.as_view(), name="support-widget-knowledge-list"),
    path("widget/<uuid:site_key>/knowledge/articles/<uuid:article_id>/", SupportWidgetKnowledgeArticleView.as_view(), name="support-widget-knowledge-article"),
    path("widget/<uuid:site_key>/knowledge/articles/<uuid:article_id>/feedback/", SupportWidgetKnowledgeFeedbackView.as_view(), name="support-widget-knowledge-feedback"),
    path("widget/<uuid:site_key>/sessions/", SupportWidgetSessionCreateView.as_view(), name="support-widget-session-create"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/", SupportWidgetSessionDetailView.as_view(), name="support-widget-session-detail"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/refresh/", SupportWidgetSessionRefreshView.as_view(), name="support-widget-session-refresh"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/conversation/messages/", SupportWidgetConversationMessagesView.as_view(), name="support-widget-conversation-messages"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/conversation/uploads/", SupportWidgetConversationUploadView.as_view(), name="support-widget-conversation-upload"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/conversation/read/", SupportWidgetConversationReadView.as_view(), name="support-widget-conversation-read"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/conversation/csat/", SupportWidgetConversationCSATView.as_view(), name="support-widget-conversation-csat"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/privacy/delete/", SupportWidgetVisitorDeletionRequestView.as_view(), name="support-widget-visitor-delete"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/active/", SupportWidgetActiveCallView.as_view(), name="support-widget-call-active"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/turn-credentials/", SupportWidgetCallTurnCredentialsView.as_view(), name="support-widget-call-turn"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/<uuid:call_id>/", SupportWidgetCallDetailView.as_view(), name="support-widget-call-detail"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/<uuid:call_id>/accept/", SupportWidgetCallAcceptView.as_view(), name="support-widget-call-accept"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/<uuid:call_id>/decline/", SupportWidgetCallDeclineView.as_view(), name="support-widget-call-decline"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/<uuid:call_id>/end/", SupportWidgetCallEndView.as_view(), name="support-widget-call-end"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/<uuid:call_id>/signals/", SupportWidgetCallSignalView.as_view(), name="support-widget-call-signals"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/calls/<uuid:call_id>/media-state/", SupportWidgetCallMediaStateView.as_view(), name="support-widget-call-media-state"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/attachments/<uuid:attachment_id>/download/", SupportWidgetAttachmentAccessView.as_view(), name="support-widget-attachment-download"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/attachments/<uuid:attachment_id>/preview/", SupportWidgetAttachmentPreviewView.as_view(), name="support-widget-attachment-preview"),
    path("widget/<uuid:site_key>/sessions/<uuid:session_id>/attachments/<uuid:attachment_id>/thumbnail/", SupportWidgetAttachmentThumbnailView.as_view(), name="support-widget-attachment-thumbnail"),
]
