from django.urls import path

from apps.accounts.api.views import (
    FriendRequestListCreateView,
    FriendRequestRespondView,
    NearbyUsersView,
    UserSearchView,
)

from .views import (
    ArchiveConversationView,
    AttachmentDownloadView,
    AttachmentPreviewView,
    AttachmentThumbnailView,
    ViewOnceAttachmentOpenView,
    CallAcceptView,
    CallingConfigView,
    CallDeclineView,
    CallDetailView,
    CallDiagnosticsView,
    CallEndView,
    CallHeartbeatView,
    CallListView,
    CallQualityReportView,
    RecentCallListView,
    CallMediaStateView,
    CallOrchestrationView,
    CallSignalView,
    CallSpeakerStateView,
    CallStartView,
    ChatCapabilitiesView,
    TurnCredentialsView,
    BlockDeleteView,
    BlockListCreateView,
    ConversationDetailView,
    ConversationByRouteView,
    DirectConversationByUsernameView,
    ConversationDraftView,
    ConversationE2EEKeysView,
    ConversationInviteJoinView,
    ConversationInviteLinkListCreateView,
    ConversationInviteLinkRevokeView,
    ConversationMediaGalleryView,
    ConversationNotificationSettingView,
    ConversationListCreateView,
    ConversationSearchView,
    DeviceDeactivateView,
    E2EEDeviceKeyListCreateView,
    E2EEDeviceKeyRevokeView,
    DeviceListCreateView,
    GroupOwnershipTransferView,
    GroupRouteNameAvailabilityView,
    GroupParticipantMuteView,
    GroupParticipantBanView,
    GroupParticipantManageView,
    IntegrationHealthView,
    GroupParticipantRemoveView,
    GroupParticipantRoleUpdateView,
    LeaveConversationView,
    MarkConversationDeliveredView,
    MarkConversationReadView,
    MessageDetailView,
    MessageContextView,
    MessageEditHistoryView,
    MessageListCreateView,
    MessageReportView,
    MessageForwardView,
    MessageFailView,
    MessageRetryView,
    MessageSearchView,
    MessageTranscriptView,
    MessageUpdateDeleteView,
    ModerationMessageRestoreView,
    ModerationReportDismissView,
    ModerationReportListView,
    ModerationReportResolveView,
    MuteConversationView,
    NotificationPreferenceView,
    PendingUploadDownloadView,
    PendingUploadPreviewView,
    PendingUploadThumbnailView,
    PresenceDisconnectView,
    PinConversationView,
    PresencePingView,
    MediaTokenCreateView,
    ChatAuditLogListView,
    ReactionCreateDeleteView,
    SyncView,
    UploadCreateView,
    UserStatusDeleteView,
    UserStatusListCreateView,
    UserStatusViewReceiptView,
)

urlpatterns = [
    path("capabilities/", ChatCapabilitiesView.as_view(), name="chat-capabilities"),
    path("integrations/health/", IntegrationHealthView.as_view(), name="integration-health"),
    path("calls/config/", CallingConfigView.as_view(), name="calling-config"),
    path("calls/turn-credentials/", TurnCredentialsView.as_view(), name="calling-turn-credentials"),
    path("calls/", CallListView.as_view(), name="call-list"),
    path("calls/recent/", RecentCallListView.as_view(), name="call-recent"),
    path("conversations/", ConversationListCreateView.as_view(), name="conversation-list-create"),
    path("conversations/search/", ConversationSearchView.as_view(), name="conversation-search"),
    path("conversations/group-name-availability/", GroupRouteNameAvailabilityView.as_view(), name="group-name-availability"),
    path("conversations/by-username/<str:username>/", DirectConversationByUsernameView.as_view(), name="conversation-by-username"),
    path("conversations/by-route/<str:route_key>/", ConversationByRouteView.as_view(), name="conversation-by-route"),
    path("conversations/<uuid:pk>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("conversations/<uuid:conversation_id>/draft/", ConversationDraftView.as_view(), name="conversation-draft"),
    path("conversations/<uuid:conversation_id>/e2ee/keys/", ConversationE2EEKeysView.as_view(), name="conversation-e2ee-keys"),
    path("conversations/<uuid:conversation_id>/notifications/", ConversationNotificationSettingView.as_view(), name="conversation-notifications"),
    path("conversations/<uuid:conversation_id>/media/", ConversationMediaGalleryView.as_view(), name="conversation-media"),
    path("conversations/<uuid:conversation_id>/invite-links/", ConversationInviteLinkListCreateView.as_view(), name="conversation-invite-links"),
    path("conversations/<uuid:conversation_id>/invite-links/<uuid:invite_id>/revoke/", ConversationInviteLinkRevokeView.as_view(), name="conversation-invite-revoke"),
    path("invite-links/join/", ConversationInviteJoinView.as_view(), name="conversation-invite-join"),
    path("conversations/<uuid:conversation_id>/messages/", MessageListCreateView.as_view(), name="message-list-create"),
    path("conversations/<uuid:conversation_id>/calls/start/", CallStartView.as_view(), name="call-start"),
    path("messages/search/", MessageSearchView.as_view(), name="message-search"),
    path("calls/<uuid:pk>/", CallDetailView.as_view(), name="call-detail"),
    path("calls/<uuid:call_id>/accept/", CallAcceptView.as_view(), name="call-accept"),
    path("calls/<uuid:call_id>/decline/", CallDeclineView.as_view(), name="call-decline"),
    path("calls/<uuid:call_id>/end/", CallEndView.as_view(), name="call-end"),
    path("calls/<uuid:call_id>/signal/", CallSignalView.as_view(), name="call-signal"),
    path("calls/<uuid:call_id>/heartbeat/", CallHeartbeatView.as_view(), name="call-heartbeat"),
    path("calls/<uuid:call_id>/media-state/", CallMediaStateView.as_view(), name="call-media-state"),
    path("calls/<uuid:call_id>/quality-report/", CallQualityReportView.as_view(), name="call-quality-report"),
    path("calls/<uuid:call_id>/speaker-state/", CallSpeakerStateView.as_view(), name="call-speaker-state"),
    path("calls/<uuid:call_id>/orchestration/", CallOrchestrationView.as_view(), name="call-orchestration"),
    path("calls/<uuid:call_id>/diagnostics/", CallDiagnosticsView.as_view(), name="call-diagnostics"),
    path("messages/<uuid:pk>/", MessageDetailView.as_view(), name="message-detail"),
    path("messages/<uuid:message_id>/context/", MessageContextView.as_view(), name="message-context"),
    path("messages/<uuid:message_id>/history/", MessageEditHistoryView.as_view(), name="message-edit-history"),
    path("messages/<uuid:message_id>/manage/", MessageUpdateDeleteView.as_view(), name="message-manage"),
    path("messages/<uuid:message_id>/reactions/", ReactionCreateDeleteView.as_view(), name="message-reactions"),
    path("messages/<uuid:message_id>/report/", MessageReportView.as_view(), name="message-report"),
    path("messages/<uuid:message_id>/forward/", MessageForwardView.as_view(), name="message-forward"),
    path("messages/<uuid:message_id>/fail/", MessageFailView.as_view(), name="message-fail"),
    path("messages/<uuid:message_id>/retry/", MessageRetryView.as_view(), name="message-retry"),
    path("messages/<uuid:message_id>/transcript/", MessageTranscriptView.as_view(), name="message-transcript"),
    path("conversations/<uuid:conversation_id>/mark-delivered/", MarkConversationDeliveredView.as_view(), name="conversation-mark-delivered"),
    path("conversations/<uuid:conversation_id>/mark-read/", MarkConversationReadView.as_view(), name="conversation-mark-read"),
    path("conversations/<uuid:conversation_id>/mute/", MuteConversationView.as_view(), name="conversation-mute"),
    path("conversations/<uuid:conversation_id>/archive/", ArchiveConversationView.as_view(), name="conversation-archive"),
    path("conversations/<uuid:conversation_id>/pin/", PinConversationView.as_view(), name="conversation-pin"),
    path("conversations/<uuid:conversation_id>/participants/", GroupParticipantManageView.as_view(), name="group-participant-manage"),
    path("conversations/<uuid:conversation_id>/participants/<str:user_id>/", GroupParticipantRemoveView.as_view(), name="group-participant-remove"),
    path("conversations/<uuid:conversation_id>/participants/<str:user_id>/role/", GroupParticipantRoleUpdateView.as_view(), name="group-participant-role-update"),
    path("conversations/<uuid:conversation_id>/participants/<str:user_id>/mute/", GroupParticipantMuteView.as_view(), name="group-participant-mute"),
    path("conversations/<uuid:conversation_id>/participants/<str:user_id>/ban/", GroupParticipantBanView.as_view(), name="group-participant-ban"),
    path("conversations/<uuid:conversation_id>/transfer-ownership/", GroupOwnershipTransferView.as_view(), name="group-ownership-transfer"),
    path("conversations/<uuid:conversation_id>/leave/", LeaveConversationView.as_view(), name="conversation-leave"),
    path("uploads/", UploadCreateView.as_view(), name="upload-create"),
    path("statuses/", UserStatusListCreateView.as_view(), name="user-status-list-create"),
    path("statuses/<uuid:status_id>/", UserStatusDeleteView.as_view(), name="user-status-delete"),
    path("statuses/<uuid:status_id>/view/", UserStatusViewReceiptView.as_view(), name="user-status-view"),
    path("uploads/<uuid:upload_id>/download/", PendingUploadDownloadView.as_view(), name="pending-upload-download"),
    path("uploads/<uuid:upload_id>/preview/", PendingUploadPreviewView.as_view(), name="pending-upload-preview"),
    path("uploads/<uuid:upload_id>/thumbnail/", PendingUploadThumbnailView.as_view(), name="pending-upload-thumbnail"),
    path("uploads/<uuid:resource_id>/media-token/", MediaTokenCreateView.as_view(), {"resource_type": "pending_upload"}, name="pending-upload-media-token"),
    path("attachments/<uuid:attachment_id>/download/", AttachmentDownloadView.as_view(), name="attachment-download"),
    path("attachments/<uuid:attachment_id>/preview/", AttachmentPreviewView.as_view(), name="attachment-preview"),
    path("attachments/<uuid:attachment_id>/thumbnail/", AttachmentThumbnailView.as_view(), name="attachment-thumbnail"),
    path("attachments/<uuid:resource_id>/media-token/", MediaTokenCreateView.as_view(), {"resource_type": "attachment"}, name="attachment-media-token"),
    path("attachments/<uuid:attachment_id>/view-once/open/", ViewOnceAttachmentOpenView.as_view(), name="attachment-view-once-open"),
    path("presence/ping/", PresencePingView.as_view(), name="presence-ping"),
    path("presence/disconnect/", PresenceDisconnectView.as_view(), name="presence-disconnect"),
    path("blocks/", BlockListCreateView.as_view(), name="block-list-create"),
    path("blocks/<uuid:user_id>/", BlockDeleteView.as_view(), name="block-delete"),
    path("users/search/", UserSearchView.as_view(), name="chat-user-search"),
    path("users/nearby/", NearbyUsersView.as_view(), name="chat-user-nearby"),
    path("friends/requests/", FriendRequestListCreateView.as_view(), name="chat-friend-request-list-create"),
    path("friends/requests/<uuid:request_id>/respond/", FriendRequestRespondView.as_view(), name="chat-friend-request-respond"),
    path("devices/", DeviceListCreateView.as_view(), name="device-list-create"),
    path("devices/deactivate/", DeviceDeactivateView.as_view(), name="device-deactivate"),
    path("e2ee/devices/", E2EEDeviceKeyListCreateView.as_view(), name="e2ee-device-keys"),
    path("e2ee/devices/<uuid:key_id>/revoke/", E2EEDeviceKeyRevokeView.as_view(), name="e2ee-device-key-revoke"),
    path("notifications/preferences/", NotificationPreferenceView.as_view(), name="notification-preferences"),
    path("sync/", SyncView.as_view(), name="chat-sync"),
    path("moderation/reports/", ModerationReportListView.as_view(), name="moderation-report-list"),
    path("moderation/reports/<uuid:report_id>/resolve/", ModerationReportResolveView.as_view(), name="moderation-report-resolve"),
    path("moderation/reports/<uuid:report_id>/dismiss/", ModerationReportDismissView.as_view(), name="moderation-report-dismiss"),
    path("moderation/messages/<uuid:message_id>/restore/", ModerationMessageRestoreView.as_view(), name="moderation-message-restore"),
    path("audit-logs/", ChatAuditLogListView.as_view(), name="chat-audit-log-list"),
]
