from django.urls import path

from .views import (
    AccountDeleteView,
    AvatarView,
    AccountExportView,
    EmailVerifyConfirmView,
    EmailVerifyRequestView,
    FriendRequestListCreateView,
    FriendRequestRespondView,
    LoginView,
    MeView,
    NearbyUsersView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RefreshView,
    RegisterView,
    SessionListView,
    SessionRevokeAllView,
    SessionRevokeView,
    SocialLoginView,
    UserSearchView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("social/login/", SocialLoginView.as_view(), name="social-login"),
    path("refresh/", RefreshView.as_view(), name="refresh"),
    path("password/change/", PasswordChangeView.as_view(), name="password-change"),
    path("password/reset/request/", PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("password/reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("email/verify/request/", EmailVerifyRequestView.as_view(), name="email-verify-request"),
    path("email/verify/confirm/", EmailVerifyConfirmView.as_view(), name="email-verify-confirm"),
    path("me/", MeView.as_view(), name="me"),
    path("me/avatar/", AvatarView.as_view(), name="me-avatar"),
    path("me/export/", AccountExportView.as_view(), name="account-export"),
    path("me/delete/", AccountDeleteView.as_view(), name="account-delete"),
    path("sessions/", SessionListView.as_view(), name="session-list"),
    path("sessions/revoke-all/", SessionRevokeAllView.as_view(), name="session-revoke-all"),
    path("sessions/<uuid:session_id>/revoke/", SessionRevokeView.as_view(), name="session-revoke"),
    path("users/search/", UserSearchView.as_view(), name="user-search"),
    path("users/nearby/", NearbyUsersView.as_view(), name="user-nearby"),
    path("friends/requests/", FriendRequestListCreateView.as_view(), name="friend-request-list-create"),
    path("friends/requests/<uuid:request_id>/respond/", FriendRequestRespondView.as_view(), name="friend-request-respond"),
]
