# Generated by Django 5.1.15 on 2026-07-17 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='inactive', max_length=20)),
                ('plan_code', models.CharField(blank=True, max_length=80)),
                ('website_limit', models.PositiveSmallIntegerField(default=1)),
                ('agent_limit', models.PositiveSmallIntegerField(default=1)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_support_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('max_active_conversations', models.PositiveSmallIntegerField(default=5)),
                ('can_view_all_conversations', models.BooleanField(default=False)),
                ('can_assign_conversations', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_agents_invited', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='support.supportaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_agent_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SupportWebsite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(max_length=255)),
                ('site_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('widget_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_websites_created', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='support.supportaccount')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportWebsiteAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_assignments', to='support.supportagent')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='support.supportwebsite')),
            ],
        ),
        migrations.AddIndex(
            model_name='supportaccount',
            index=models.Index(fields=['status', 'current_period_end'], name='support_sup_status_15c479_idx'),
        ),
        migrations.AddIndex(
            model_name='supportagent',
            index=models.Index(fields=['support_account', 'is_active'], name='support_sup_support_eed941_idx'),
        ),
        migrations.AddIndex(
            model_name='supportagent',
            index=models.Index(fields=['user', 'is_active'], name='support_sup_user_id_281787_idx'),
        ),
        migrations.AddIndex(
            model_name='supportagent',
            index=models.Index(fields=['support_account', 'availability', 'is_active'], name='support_sup_support_e1778b_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportagent',
            constraint=models.UniqueConstraint(fields=('support_account', 'user'), name='uniq_support_account_agent'),
        ),
        migrations.AddIndex(
            model_name='supportwebsite',
            index=models.Index(fields=['support_account', 'is_active'], name='support_sup_support_4228b8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportwebsite',
            index=models.Index(fields=['site_key'], name='support_sup_site_ke_15740b_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportwebsite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('support_account', 'domain'), name='uniq_active_support_website_domain'),
        ),
        migrations.AddIndex(
            model_name='supportwebsiteagent',
            index=models.Index(fields=['website', 'agent'], name='support_sup_website_d86b42_idx'),
        ),
        migrations.AddIndex(
            model_name='supportwebsiteagent',
            index=models.Index(fields=['agent', 'website'], name='support_sup_agent_i_764d1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportwebsiteagent',
            constraint=models.UniqueConstraint(fields=('website', 'agent'), name='uniq_support_website_agent'),
        ),
    ]
