# Generated by Django 5.1.15 on 2026-07-17 17:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def create_widget_settings(apps, schema_editor):
    SupportWebsite = apps.get_model("support", "SupportWebsite")
    SupportWidgetSettings = apps.get_model("support", "SupportWidgetSettings")
    for website in SupportWebsite.objects.all().iterator():
        SupportWidgetSettings.objects.get_or_create(
            website_id=website.id,
            defaults={"brand_name": f"{website.name} Support"},
        )


def remove_widget_settings(apps, schema_editor):
    SupportWidgetSettings = apps.get_model("support", "SupportWidgetSettings")
    SupportWidgetSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_agent_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('locale', models.CharField(blank=True, max_length=32)),
                ('current_page_url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='support.supportwebsite')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportWidgetSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('origin', models.URLField(max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('current_page_url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_sessions', to='support.supportvisitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_sessions', to='support.supportwebsite')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportWidgetSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Support', max_length=120)),
                ('primary_color', models.CharField(default='#111111', max_length=7)),
                ('welcome_text', models.CharField(default='Hi, how can we help?', max_length=255)),
                ('offline_text', models.CharField(default='Leave a message and our team will reply soon.', max_length=255)),
                ('launcher_text', models.CharField(default='Chat', max_length=60)),
                ('privacy_note', models.CharField(blank=True, max_length=180)),
                ('position', models.CharField(choices=[('right', 'Bottom right'), ('left', 'Bottom left')], default='right', max_length=20)),
                ('theme', models.CharField(choices=[('auto', 'Automatic'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=20)),
                ('require_name', models.BooleanField(default=False)),
                ('require_email', models.BooleanField(default=False)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_settings', to='support.supportwebsite')),
            ],
            options={
                'verbose_name_plural': 'Support widget settings',
            },
        ),
        migrations.RunPython(create_widget_settings, remove_widget_settings),
        migrations.AddIndex(
            model_name='supportvisitor',
            index=models.Index(fields=['website', 'last_seen_at'], name='support_visitor_site_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='supportvisitor',
            index=models.Index(fields=['website', 'is_blocked'], name='support_visitor_site_block_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportvisitor',
            constraint=models.UniqueConstraint(fields=('website', 'external_id'), name='uniq_support_visitor_external_id'),
        ),
        migrations.AddIndex(
            model_name='supportwidgetsession',
            index=models.Index(fields=['website', 'status', 'last_seen_at'], name='sup_wsess_site_stat_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='supportwidgetsession',
            index=models.Index(fields=['visitor', 'status', 'expires_at'], name='sup_wsess_vis_stat_exp_idx'),
        ),
    ]
