# Generated by Django 5.1.15 on 2026-07-17 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_pendingupload_purpose_alter_messageattachment_file_and_more'),
        ('support', '0004_support_conversations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPendingUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('team', 'Support team'), ('visitor', 'Website visitor')], max_length=16)),
                ('pending_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_upload', to='chat.pendingupload')),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='support.supportaccount')),
                ('support_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='support.supportconversation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_pending_uploads', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='support.supportvisitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='support.supportwebsite')),
                ('widget_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to='support.supportwidgetsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['support_account', 'website', 'created_at'], name='sup_upload_acct_site_time_idx'), models.Index(fields=['source', 'created_at'], name='sup_upload_source_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source', 'team'), ('uploaded_by__isnull', False), ('visitor__isnull', True), ('widget_session__isnull', True)), models.Q(('source', 'visitor'), ('uploaded_by__isnull', True), ('visitor__isnull', False), ('widget_session__isnull', False)), _connector='OR'), name='support_upload_valid_owner')],
            },
        ),
    ]
