# Generated by Django 5.1.15 on 2026-07-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_supportpendingupload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(default="#4f46e5", max_length=7)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_tags_created", to=settings.AUTH_USER_MODEL)),
                ("support_account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="support.supportaccount")),
            ],
            options={
                "ordering": ["name", "created_at"],
                "indexes": [models.Index(fields=["support_account", "is_active"], name="sup_tag_acct_active_idx")],
                "constraints": [models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("support_account"), condition=models.Q(("is_active", True)), name="uniq_sup_active_tag_name_ci")],
            },
        ),
        migrations.CreateModel(
            name="SupportInternalNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=10000)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="support_internal_notes", to=settings.AUTH_USER_MODEL)),
                ("support_conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="internal_notes", to="support.supportconversation")),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["support_conversation", "created_at"], name="sup_note_conv_time_idx")],
            },
        ),
        migrations.CreateModel(
            name="SupportCannedReply",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shortcut", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(max_length=10000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_canned_replies_created", to=settings.AUTH_USER_MODEL)),
                ("support_account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="canned_replies", to="support.supportaccount")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_canned_replies_updated", to=settings.AUTH_USER_MODEL)),
                ("website", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="canned_replies", to="support.supportwebsite")),
            ],
            options={
                "ordering": ["shortcut", "title"],
                "indexes": [
                    models.Index(fields=["support_account", "is_active"], name="sup_reply_acct_active_idx"),
                    models.Index(fields=["website", "is_active"], name="sup_reply_site_active_idx"),
                ],
                "constraints": [models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("support_account", "shortcut"), name="uniq_sup_active_reply_shortcut")],
            },
        ),
        migrations.CreateModel(
            name="SupportAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("target_type", models.CharField(blank=True, max_length=40)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("summary", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_audit_events", to=settings.AUTH_USER_MODEL)),
                ("support_account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="support.supportaccount")),
                ("support_conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="support.supportconversation")),
                ("website", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="support.supportwebsite")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["support_account", "created_at"], name="sup_audit_acct_time_idx"),
                    models.Index(fields=["support_conversation", "created_at"], name="sup_audit_conv_time_idx"),
                    models.Index(fields=["actor", "created_at"], name="sup_audit_actor_time_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportConversationTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("added_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_conversation_tags_added", to=settings.AUTH_USER_MODEL)),
                ("support_conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tag_assignments", to="support.supportconversation")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversation_assignments", to="support.supporttag")),
            ],
            options={
                "indexes": [models.Index(fields=["support_conversation", "tag"], name="sup_conv_tag_lookup_idx")],
                "constraints": [models.UniqueConstraint(fields=("support_conversation", "tag"), name="uniq_support_conversation_tag")],
            },
        ),
        migrations.CreateModel(
            name="SupportSavedInboxView",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("queue", models.CharField(blank=True, max_length=24)),
                ("status", models.CharField(blank=True, max_length=24)),
                ("priority", models.CharField(blank=True, max_length=16)),
                ("search", models.CharField(blank=True, max_length=120)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("support_account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_inbox_views", to="support.supportaccount")),
                ("tag", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="saved_inbox_views", to="support.supporttag")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="support_saved_inbox_views", to=settings.AUTH_USER_MODEL)),
                ("website", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saved_inbox_views", to="support.supportwebsite")),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "indexes": [models.Index(fields=["support_account", "user"], name="sup_saved_view_user_idx")],
                "constraints": [models.UniqueConstraint(django.db.models.functions.text.Lower("name"), models.F("support_account"), models.F("user"), name="uniq_sup_saved_view_name_ci")],
            },
        ),
    ]
