# Generated by Django 5.1.15 on 2026-07-18 04:07

import apps.support.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_pendingupload_purpose_alter_messageattachment_file_and_more'),
        ('support', '0006_support_workflow_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportServiceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('first_response_due_soon', 'First response due soon'), ('first_response_overdue', 'First response overdue'), ('next_response_due_soon', 'Next response due soon'), ('next_response_overdue', 'Next response overdue'), ('resolution_due_soon', 'Resolution due soon'), ('resolution_overdue', 'Resolution overdue'), ('follow_up_due', 'Follow-up due')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('resolved', 'Resolved')], db_index=True, default='unread', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportServiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('business_hours_enabled', models.BooleanField(default=True)),
                ('business_hours', models.JSONField(default=apps.support.models.default_support_business_hours)),
                ('first_response_targets', models.JSONField(default=apps.support.models.default_first_response_targets)),
                ('next_response_targets', models.JSONField(default=apps.support.models.default_next_response_targets)),
                ('resolution_targets', models.JSONField(default=apps.support.models.default_resolution_targets)),
                ('due_soon_minutes', models.PositiveSmallIntegerField(default=15)),
                ('default_follow_up_minutes', models.PositiveIntegerField(default=1440)),
                ('alert_owner', models.BooleanField(default=True)),
                ('alert_assigned_agent', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Support service settings',
            },
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='first_response_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='follow_up_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='follow_up_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_follow_ups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='follow_up_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='next_response_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='next_response_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='resolution_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', 'first_response_due_at'], name='sup_conv_first_due_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', 'next_response_due_at'], name='sup_conv_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', 'resolution_due_at'], name='sup_conv_res_due_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', 'follow_up_at'], name='sup_conv_follow_due_idx'),
        ),
        migrations.AddField(
            model_name='supportservicealert',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_service_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportservicealert',
            name='support_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alerts', to='support.supportaccount'),
        ),
        migrations.AddField(
            model_name='supportservicealert',
            name='support_conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alerts', to='support.supportconversation'),
        ),
        migrations.AddField(
            model_name='supportservicealert',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alerts', to='support.supportwebsite'),
        ),
        migrations.AddField(
            model_name='supportservicesettings',
            name='support_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='support.supportaccount'),
        ),
        migrations.AddField(
            model_name='supportservicesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_service_settings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supportservicealert',
            index=models.Index(fields=['recipient', 'status', 'triggered_at'], name='sup_alert_user_stat_time_idx'),
        ),
        migrations.AddIndex(
            model_name='supportservicealert',
            index=models.Index(fields=['support_account', 'status', 'due_at'], name='sup_alert_acct_stat_due_idx'),
        ),
        migrations.AddIndex(
            model_name='supportservicealert',
            index=models.Index(fields=['support_conversation', 'kind'], name='sup_alert_conv_kind_idx'),
        ),
    ]
