# Generated by Django 5.1.15 on 2026-07-18 04:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_service_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFeedbackSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csat_enabled', models.BooleanField(default=True)),
                ('auto_request_on_resolve', models.BooleanField(default=True)),
                ('allow_comment', models.BooleanField(default=True)),
                ('survey_expiry_days', models.PositiveSmallIntegerField(default=30)),
                ('support_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_settings', to='support.supportaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_feedback_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Support feedback settings',
            },
        ),
        migrations.CreateModel(
            name='SupportCSATSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_csat_requests_created', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_surveys', to='support.supportaccount')),
                ('support_conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat_survey', to='support.supportconversation')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_surveys', to='support.supportwebsite')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['support_account', 'status', 'requested_at'], name='sup_csat_acct_stat_req_idx'), models.Index(fields=['website', 'status', 'submitted_at'], name='sup_csat_site_stat_sub_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='support_csat_rating_1_to_5')],
            },
        ),
    ]
