# Generated by Django 5.1.15 on 2026-07-18 04:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_analytics_and_customer_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportKnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=320)),
                ('body', models.TextField(max_length=30000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('all_websites', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_knowledge_articles_created', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to='support.supportaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_knowledge_articles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportKnowledgeArticleWebsite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_assignments', to='support.supportknowledgearticle')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_article_assignments', to='support.supportwebsite')),
            ],
        ),
        migrations.AddField(
            model_name='supportknowledgearticle',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='knowledge_articles', through='support.SupportKnowledgeArticleWebsite', to='support.supportwebsite'),
        ),
        migrations.CreateModel(
            name='SupportKnowledgeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_knowledge_categories_created', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_categories', to='support.supportaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_knowledge_categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportknowledgearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='support.supportknowledgecategory'),
        ),
        migrations.CreateModel(
            name='SupportKnowledgeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_key_hash', models.CharField(max_length=64)),
                ('helpful', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='support.supportknowledgearticle')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_feedback_entries', to='support.supportwebsite')),
            ],
        ),
        migrations.CreateModel(
            name='SupportKnowledgeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('show_in_widget', models.BooleanField(default=True)),
                ('suggestions_enabled', models.BooleanField(default=True)),
                ('allow_article_feedback', models.BooleanField(default=True)),
                ('max_suggestions', models.PositiveSmallIntegerField(default=5)),
                ('support_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_settings', to='support.supportaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_knowledge_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Support knowledge settings',
            },
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticlewebsite',
            index=models.Index(fields=['website', 'article'], name='sup_kb_site_article_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportknowledgearticlewebsite',
            constraint=models.UniqueConstraint(fields=('article', 'website'), name='uniq_support_kb_article_website'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgecategory',
            index=models.Index(fields=['support_account', 'is_active', 'sort_order'], name='sup_kb_cat_acct_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportknowledgecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('support_account'), condition=models.Q(('is_active', True)), name='uniq_sup_active_kb_category_ci'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticle',
            index=models.Index(fields=['support_account', 'status', 'is_featured'], name='sup_kb_art_acct_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticle',
            index=models.Index(fields=['category', 'status'], name='sup_kb_art_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgearticle',
            index=models.Index(fields=['published_at'], name='sup_kb_art_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportknowledgearticle',
            constraint=models.UniqueConstraint(fields=('support_account', 'slug'), name='uniq_support_kb_article_slug'),
        ),
        migrations.AddIndex(
            model_name='supportknowledgefeedback',
            index=models.Index(fields=['website', 'created_at'], name='sup_kb_feedback_site_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportknowledgefeedback',
            constraint=models.UniqueConstraint(fields=('article', 'website', 'client_key_hash'), name='uniq_support_kb_client_feedback'),
        ),
    ]
