# Generated by Django 5.1.15 on 2026-07-18 05:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_knowledge_base_self_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_enabled', models.BooleanField(default=False)),
                ('resolved_conversation_retention_days', models.PositiveIntegerField(default=730)),
                ('widget_session_retention_days', models.PositiveIntegerField(default=90)),
                ('export_retention_days', models.PositiveSmallIntegerField(default=7)),
                ('allow_visitor_deletion_requests', models.BooleanField(default=True)),
                ('include_attachments_in_exports', models.BooleanField(default=False)),
                ('support_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='support.supportaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_privacy_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Support privacy settings',
            },
        ),
        migrations.CreateModel(
            name='SupportWebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=1000)),
                ('signing_secret', models.CharField(max_length=128)),
                ('event_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_webhook_endpoints_created', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='support.supportaccount')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportWebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.CharField(blank=True, max_length=1000)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='support.supportwebhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportDataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('file', models.FileField(blank=True, max_length=500, upload_to='support/exports/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('record_counts', models.JSONField(blank=True, default=dict)),
                ('include_attachments', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_data_exports_requested', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='support.supportaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['support_account', 'status', 'created_at'], name='sup_export_acct_stat_idx'), models.Index(fields=['status', 'expires_at'], name='sup_export_stat_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportVisitorDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_external_id', models.UUIDField()),
                ('source', models.CharField(choices=[('owner', 'Owner'), ('visitor', 'Visitor'), ('retention', 'Retention')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_visitor_deletions_requested', to=settings.AUTH_USER_MODEL)),
                ('support_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_deletion_requests', to='support.supportaccount')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='support.supportvisitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_deletion_requests', to='support.supportwebsite')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['support_account', 'status', 'requested_at'], name='sup_delete_acct_stat_idx'), models.Index(fields=['website', 'visitor_external_id'], name='sup_delete_site_ext_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('website', 'visitor_external_id'), name='uniq_active_support_visitor_delete')],
            },
        ),
        migrations.AddIndex(
            model_name='supportwebhookendpoint',
            index=models.Index(fields=['support_account', 'is_active'], name='sup_hook_acct_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportwebhookendpoint',
            constraint=models.UniqueConstraint(fields=('support_account', 'name'), name='uniq_support_webhook_name'),
        ),
        migrations.AddIndex(
            model_name='supportwebhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='sup_hook_del_stat_next_idx'),
        ),
        migrations.AddIndex(
            model_name='supportwebhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='sup_hook_del_ep_time_idx'),
        ),
    ]
