# Generated by Django 5.1.15 on 2026-07-18 05:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_integrations_data_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportwidgetsettings',
            name='allow_audio_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportwidgetsettings',
            name='allow_video_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SupportCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], max_length=16)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('ongoing', 'Ongoing'), ('declined', 'Declined'), ('missed', 'Missed'), ('ended', 'Ended'), ('failed', 'Failed')], db_index=True, default='ringing', max_length=16)),
                ('room_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=64)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_support_calls', to=settings.AUTH_USER_MODEL)),
                ('support_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='support.supportconversation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportCallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('team', 'Support team'), ('visitor', 'Website visitor')], max_length=16)),
                ('state', models.CharField(choices=[('ringing', 'Ringing'), ('joined', 'Joined'), ('declined', 'Declined'), ('missed', 'Missed'), ('left', 'Left')], max_length=16)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_call_participations', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to='support.supportvisitor')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='support.supportcallsession')),
            ],
        ),
        migrations.CreateModel(
            name='SupportCallSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('allow_video', models.BooleanField(default=True)),
                ('max_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('support_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_settings', to='support.supportaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_call_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Support call settings',
            },
        ),
        migrations.CreateModel(
            name='SupportCallSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_kind', models.CharField(choices=[('team', 'Support team'), ('visitor', 'Website visitor')], max_length=16)),
                ('recipient_kind', models.CharField(choices=[('team', 'Support team'), ('visitor', 'Website visitor')], max_length=16)),
                ('signal_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('signal_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='support.supportcallsession')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_call_signals_sent', to=settings.AUTH_USER_MODEL)),
                ('sender_visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_signals_sent', to='support.supportvisitor')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportcallsession',
            index=models.Index(fields=['support_conversation', '-started_at'], name='sup_call_conv_time_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcallsession',
            index=models.Index(fields=['status', '-started_at'], name='sup_call_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcallsession',
            index=models.Index(fields=['initiated_by', 'status'], name='sup_call_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportcallsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ringing', 'ongoing'])), fields=('support_conversation',), name='uniq_active_support_call_conversation'),
        ),
        migrations.AddConstraint(
            model_name='supportcallsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ringing', 'ongoing'])), fields=('initiated_by',), name='uniq_active_support_call_initiator'),
        ),
        migrations.AddIndex(
            model_name='supportcallparticipant',
            index=models.Index(fields=['call', 'kind'], name='sup_call_part_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcallparticipant',
            index=models.Index(fields=['user', 'state'], name='sup_call_part_user_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcallparticipant',
            index=models.Index(fields=['visitor', 'state'], name='sup_call_part_visit_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportcallparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'team'), ('user__isnull', False), ('visitor__isnull', True)), models.Q(('kind', 'visitor'), ('user__isnull', True), ('visitor__isnull', False)), _connector='OR'), name='support_call_participant_identity'),
        ),
        migrations.AddConstraint(
            model_name='supportcallparticipant',
            constraint=models.UniqueConstraint(fields=('call', 'kind'), name='uniq_support_call_participant_kind'),
        ),
        migrations.AddIndex(
            model_name='supportcallsignal',
            index=models.Index(fields=['call', 'recipient_kind', 'created_at'], name='sup_call_signal_recv_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcallsignal',
            index=models.Index(fields=['call', 'consumed_at'], name='sup_call_signal_cons_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportcallsignal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender_kind', 'team'), ('sender_user__isnull', False), ('sender_visitor__isnull', True)), models.Q(('sender_kind', 'visitor'), ('sender_user__isnull', True), ('sender_visitor__isnull', False)), _connector='OR'), name='support_call_signal_sender_identity'),
        ),
    ]
