# Generated by Django 5.1.15 on 2026-07-21 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_automations_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportconversation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('waiting_customer', 'Waiting for customer'), ('waiting_team', 'Waiting for team'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=24),
        ),
        migrations.AlterField(
            model_name='supportconversationfollower',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportconversationtransfer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportinternalnotemention',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
