# Generated by Django 5.2.13 on 2026-04-10 16:12

import apps.chat.models
import apps.chat.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat/conversation_avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('direct_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], max_length=16)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('ongoing', 'Ongoing'), ('declined', 'Declined'), ('missed', 'Missed'), ('ended', 'Ended'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('room_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_calls', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.conversation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='chat.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conversation_invite_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationNotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_notifications_enabled', models.BooleanField(default=True)),
                ('call_notifications_enabled', models.BooleanField(default=True)),
                ('mentions_only', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('system', 'System')], default='text', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_temp_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=16)),
                ('failed_reason', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='chat.message')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_muted_until', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.CharField(blank=True, max_length=255)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_bans_issued', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
                ('last_delivered_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.CreateModel(
            name='ChatAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('message_sent', 'Message sent'), ('message_edited', 'Message edited'), ('message_deleted', 'Message deleted'), ('message_restored', 'Message restored'), ('reaction_added', 'Reaction added'), ('reaction_removed', 'Reaction removed'), ('delivery_marked', 'Delivery marked'), ('read_marked', 'Read marked'), ('participants_added', 'Participants added'), ('participant_removed', 'Participant removed'), ('role_changed', 'Role changed'), ('ownership_transferred', 'Ownership transferred'), ('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('report_created', 'Report created'), ('moderation_action', 'Moderation action'), ('upload_scanned', 'Upload scanned'), ('media_token_issued', 'Media token issued'), ('media_accessed', 'Media accessed'), ('call_started', 'Call started'), ('call_joined', 'Call joined'), ('call_declined', 'Call declined'), ('call_ended', 'Call ended'), ('call_signal_sent', 'Call signal sent'), ('participant_muted', 'Participant muted'), ('participant_banned', 'Participant banned'), ('participant_unbanned', 'Participant unbanned'), ('message_failed', 'Message failed'), ('message_retried', 'Message retried')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='chat.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='chat.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.chat.storage.attachment_storage_factory, upload_to='chat/attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed')], default='clean', max_length=20)),
                ('scan_notes', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_text', models.TextField(blank=True)),
                ('new_text', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_edit_history', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='chat.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=32)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate', 'Hate'), ('violence', 'Violence'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('language_code', models.CharField(blank=True, max_length=16)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='chat.message')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('resolve_report', 'Resolve report'), ('dismiss_report', 'Dismiss report'), ('hide_message', 'Hide message'), ('restore_message', 'Restore message')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='chat.message')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='chat.messagereport')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('message_preview_enabled', models.BooleanField(default=True)),
                ('mute_all', models.BooleanField(default=False)),
                ('call_quality_preference', models.CharField(choices=[('auto', 'Auto'), ('low', 'Low'), ('mid', 'Mid'), ('clear', 'Clear')], default='auto', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.chat.storage.pending_upload_storage_factory, upload_to='chat/pending/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attached', 'Attached'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scan_notes', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.chat.models.pending_upload_expiry_default)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_initiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=20)),
                ('push_token', models.CharField(db_index=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('invited', 'Invited'), ('ringing', 'Ringing'), ('joined', 'Joined'), ('declined', 'Declined'), ('missed', 'Missed'), ('left', 'Left')], default='invited', max_length=20)),
                ('network_quality', models.CharField(choices=[('unknown', 'Unknown'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('offline', 'Offline')], default='unknown', max_length=20)),
                ('preferred_video_quality', models.CharField(choices=[('auto', 'Auto'), ('off', 'Off'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='auto', max_length=16)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('is_on_hold', models.BooleanField(default=False)),
                ('reconnecting', models.BooleanField(default=False)),
                ('connection_state', models.CharField(choices=[('new', 'New'), ('checking', 'Checking'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('disconnected', 'Disconnected'), ('failed', 'Failed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('audio_route', models.CharField(choices=[('auto', 'Auto'), ('speaker', 'Speaker'), ('earpiece', 'Earpiece'), ('bluetooth', 'Bluetooth'), ('wired', 'Wired')], default='auto', max_length=16)),
                ('screen_share_enabled', models.BooleanField(default=False)),
                ('screen_share_started_at', models.DateTimeField(blank=True, null=True)),
                ('raised_hand_at', models.DateTimeField(blank=True, null=True)),
                ('is_speaking', models.BooleanField(default=False)),
                ('speaking_level', models.PositiveSmallIntegerField(default=0)),
                ('last_spoke_at', models.DateTimeField(blank=True, null=True)),
                ('reconnect_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('last_quality_report_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_signal_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('packet_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jitter_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('round_trip_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(default=100)),
                ('quality_alert', models.CharField(blank=True, max_length=32)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.callsession')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'state'], name='chat_callpa_user_id_f0f4d6_idx'), models.Index(fields=['call', 'network_quality'], name='chat_callpa_call_id_db7144_idx'), models.Index(fields=['call', 'last_heartbeat_at'], name='chat_callpa_call_id_1ef51a_idx'), models.Index(fields=['call', 'connection_state'], name='chat_callpa_call_id_c62978_idx'), models.Index(fields=['call', 'raised_hand_at'], name='chat_callpa_call_id_2796b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('call', 'user'), name='uniq_call_user_participant')],
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation', '-started_at'], name='chat_callse_convers_498a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', '-started_at'], name='chat_callse_status_ca817e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationinvitelink',
            index=models.Index(fields=['conversation', 'revoked_at', 'expires_at'], name='chat_conver_convers_f53018_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationnotificationsetting',
            index=models.Index(fields=['user', 'conversation'], name='chat_conver_user_id_d65cb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationnotificationsetting',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_conversation_notification_setting'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_messag_convers_d0740f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__62c9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'conversation'], name='chat_conver_user_id_6818d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'joined_at'], name='chat_conver_convers_c7e5df_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_conversation_user_participant'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type', 'last_message_at'], name='chat_conver_type_e9751f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='chat_chatau_event_t_3ab298_idx'),
        ),
        migrations.AddIndex(
            model_name='chatauditlog',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_chatau_convers_43a54f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['user', 'delivered_at'], name='chat_messag_user_id_ef9a8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_message_delivery_user'),
        ),
        migrations.AddIndex(
            model_name='messageedithistory',
            index=models.Index(fields=['message', '-created_at'], name='chat_messag_message_cb6ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'created_at'], name='chat_messag_message_bbd71c_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_message_user_emoji_reaction'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['reason', 'created_at'], name='chat_messag_reason_024882_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('message', 'reporter'), name='uniq_message_report_reporter'),
        ),
        migrations.AddIndex(
            model_name='messagetranscript',
            index=models.Index(fields=['status', 'updated_at'], name='chat_messag_status_7d92cc_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', 'created_at'], name='chat_modera_action__03732b_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingupload',
            index=models.Index(fields=['user', 'status', 'created_at'], name='chat_pendin_user_id_f18139_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingupload',
            index=models.Index(fields=['user', 'expires_at'], name='chat_pendin_user_id_46b7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker', 'blocked'], name='chat_userbl_blocker_343807_idx'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_blocker_blocked'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'push_token'), name='uniq_user_push_token'),
        ),
    ]
