# Generated by Django 5.1.15 on 2026-07-17 20:02

import apps.chat.models
import apps.chat.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_sender_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingupload',
            name='purpose',
            field=models.CharField(choices=[('messenger', 'Messenger'), ('support', 'Support Chat')], db_index=True, default='messenger', max_length=16),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(max_length=500, storage=apps.chat.storage.attachment_storage_factory, upload_to=apps.chat.models.message_attachment_path),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=apps.chat.storage.attachment_storage_factory, upload_to=apps.chat.models.message_attachment_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='file',
            field=models.FileField(max_length=500, storage=apps.chat.storage.pending_upload_storage_factory, upload_to=apps.chat.models.pending_upload_path),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=apps.chat.storage.pending_upload_storage_factory, upload_to=apps.chat.models.pending_upload_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='pendingupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pendingupload',
            index=models.Index(fields=['purpose', 'status', 'created_at'], name='chat_pendin_purpose_cd1cf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pendingupload',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'support'), ('user__isnull', False), _connector='OR'), name='chat_pending_messenger_user_required'),
        ),
    ]
